/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DllInterfacePkg_PointHandleInterface */

#ifndef _Included_DllInterfacePkg_PointHandleInterface
#define _Included_DllInterfacePkg_PointHandleInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DllInterfacePkg_PointHandleInterface
 * Method:    PointHandleByC
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_DllInterfacePkg_PointHandleInterface_PointHandleByC
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
